### PR TITLE
Non-permissive additive index generation

### PR DESCRIPTION
**Pull request by amisstea**
The index generation task needs creds to pull from all private registries.
This requires the user to provide the terms-based registry creds
themselves rather than using the cluster-scoped secret because they
aren't accessible to OPM inside the container.

### CODE REVIEW

**Review by wcheang — APPROVED** [review]
I don't think I know enough to be able to spot anything wrong at this point, but it looks okay to me as far as my understanding goes :+1:

**Comment by haripate** [comment]
Looks good to me!

**Review by haripate — APPROVED** [review]
Looks good to me!

**Comment by MarcinGinszt** [comment]
LGTM

**Review by MarcinGinszt — APPROVED** [review]

**Pull request merged**
