### PR TITLE
 Added opm CLI for ppc64le architecture

### PR DESCRIPTION
**Pull request by mayurwaghmode**

### CODE REVIEW

**Comment by mayurwaghmode** [comment]
@Allda Can you please review the PR?

**Review by Allda — COMMENTED** [review]
Can you please explain what's the goal of this change? I see you changed the source from the official opm mirror to your custom. What's the difference and how it this going to be supported?

**Comment by mayurwaghmode** [comment]
Using the official OPM mirror we were facing the "unable to DeployableByOLM" issue at the preflight stage. Official OPM mirror contains a different version than the [official OPM ](https://github.com/operator-framework/operator-registry/releases). Officially OPM doesn't have the ppc64le support, we have [opened a PR]( https://github.com/operator-framework/operator-registry/pull/631) to get ppc64le support but it is taking time. So we are using a custom-built OPM binary.

**Comment by Allda** [comment]
@mayurwaghmode ok that makes sense. I am merging for now to unlock you. Please change it back to the official mirror when the PR is merged.

**Review by Allda — APPROVED** [review]

**Comment by mayurwaghmode** [comment]
Thanks, @Allda! Sure I will Change back.

**Pull request merged**
