### PR TITLE
Upload community pipelines logs to Gists

### PR DESCRIPTION
**Pull request by Allda**
Community hosted and release pipelines uploads logs to Github gists and share them to the associated PR.

This commit also adds a pipeline summary to the pipelines.

JIRA: ISV-3831

### CODE REVIEW

**Comment by Allda** [comment]
The example of the PR comment can be found here: https://github.com/redhat-openshift-ecosystem/community-operators-pipeline-preprod/pull/1

**Comment by Allda** [comment]
> Looks good but can we make it so that we only get a single comment to the PR instead of two? For example we could have the upload-community-pipeline-logs task return the URL of the uploaded logs and pass it as an optional input to the github-pipelinerun-summary task and modify it so that when a link is provided, the "pipeline run" field in the summary is rendered as a link to the gist. WDYT?

I have already tried that but unfortunately, Tekton doesn't allow to have dependencies using references in the `finally` section. A task in a finally section can't re-use the result from another task that is also in the finally section.

**Comment by Allda** [comment]
@mporrato I managed to re-arange the code a bit and I was able to inject the log URL to the summary comment. You can check it here: https://github.com/redhat-openshift-ecosystem/community-operators-pipeline-preprod/pull/1#issuecomment-1655294991

I'll post an updated code today for review.

**Comment by Allda** [comment]
@mporrato The new code is ready for review.

**Review by mporrato — APPROVED** [review]
Nice!

**Review by haripate — APPROVED** [review]
LGTM

**Pull request merged**
