### PR TITLE
[ISV-3353] The preflight-trigger image tag needs to be changed in the task definition.

### PR DESCRIPTION
**Pull request by haripate**

### CODE REVIEW

**Comment by johnbe11** [comment]
LGTM

**Comment by acornett21** [comment]
We don't actually want this task pointing to `latest` we want it pointing to `stable`. This keeps with consistency across the different containers (preflight-trigger/preflight/etc).

**Review by mrhillsman — COMMENTED** [review]
/do-not-merge

**Comment by haripate** [comment]
Closing the PR as no change is required.

**Pull request closed without merging**
