### PR TITLE
ISV-4029: remove obselete/unused CA

### PR DESCRIPTION
**Pull request by johnbe11**

### CODE REVIEW

**Comment by johnbe11** [comment]
@mporrato PTAL

**Comment by johnbe11** [comment]
@mporrato fyi - rebased to pick up your CVE fix

**Comment by johnbe11** [comment]
@mporrato one is already expired, and the other is about to expire.  Neither of them are used/referenced by the project.

**Comment by mporrato** [comment]
> @mporrato one is already expired, and the other is about to expire. Neither of them are used/referenced by the project.

It's being copied into the container image in https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/d166012e2b7a680d2802e56b57b3b6b5428c4b51/operator-pipeline-images/Dockerfile#L14 but I see we already have the 2022 CA cert so we should be fine :crossed_fingers:

**Pull request merged**
