### PR TITLE
Remove repo published argument in create_container_image.py

### PR DESCRIPTION
**Pull request by johnbieren**
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
> Can you please provide more details about the change and explain why it is needed?
> 
> I see the argument was defined but never used. Since the pipeline will always produce images with the published set to True I am leaning toward removing the argument completely.
> 
> Also, the argument is stored as a string which is not compatible with the container image schema that requires a boolean.

It isn't needed. I was just trying to fix what looks like a bug (the argument being defined, but not used). I can change the PR to just remove the argument all together then

**Comment by Allda** [comment]
Thank you for the explanation. Since the argument is irrelevant I would instead remove it entirely from a code. If you are ok with removing it please update the PR. Otherwise, we will address this code change in other PR in upcoming releases.

**Comment by Allda** [comment]
@johnbieren Looks good, there is one more place where this arg is used. Please also remove it from there: https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/ansible/roles/operator-pipeline/templates/openshift/tasks/create-container-image.yml#L91

**Comment by johnbieren** [comment]
> @johnbieren Looks good, there is one more place where this arg is used. Please also remove it from there: https://github.com/redhat-openshift-ecosystem/operator-pipelines/blob/main/ansible/roles/operator-pipeline/templates/openshift/tasks/create-container-image.yml#L91

fixed, thanks

**Review by Allda — APPROVED** [review]

**Pull request merged**
