### PR TITLE
updating workflow of building multi-arch images for reducing the build-time

### PR DESCRIPTION
**Pull request by mayurwaghmode**
This PR will reduce the build time for building and publishing the multi-arch images, also it will remove the dependency of maintaining the multiple Dockerfiles for different architectures.

### CODE REVIEW

**Comment by mayurwaghmode** [comment]
@Allda @amisstea can u please take a look at this PR?

**Review by amisstea — COMMENTED** [review]
Can we also remove the arch-specific Dockerfiles now?

**Comment by mayurwaghmode** [comment]
> Can we also remove the arch-specific Dockerfiles now?

yes, we can remove now :)

**Comment by mayurwaghmode** [comment]
> Can we also remove the arch-specific Dockerfiles now?

@amisstea Done

**Review by amisstea — APPROVED** [review]
LGTM :+1: 

I filed https://issues.redhat.com/browse/ISV-2486 to switch the CI/CD over to these multiarch images.

**Comment by mayurwaghmode** [comment]
> LGTM 👍
> 
> I filed https://issues.redhat.com/browse/ISV-2486 to switch the CI/CD over to these multiarch images.

Thanks @amisstea

**Pull request merged**
