### PR TITLE
ISV-4298: override default timeout values for Import *-index imagestr…

### PR DESCRIPTION
**Pull request by johnbe11**
ISV-4298: override default timeout values for Import *-index imagestream tasks, to mitigate increased response times from import request

(timeout specified as integer seconds, default is 30)

### CODE REVIEW

**Comment by johnbe11** [comment]
@Allda PTAL

**Comment by Allda** [comment]
Can you please also add a tag to the ansible task and skip it during a deployment to real env? The import is only needed for integration tests.

**Review by Allda — CHANGES_REQUESTED** [review]
As mentioned in the private chat this PR needs to be tested against real ocp instance to test if increased timeout is not ignored by the default timeout of OCP API.

**Review by Allda — APPROVED** [review]
Looks good to me :) Please confirm the timeout works as expected in parallel. I would like to merge this ASAP to no longer block releases.

**Pull request merged**
