### PR TITLE
[ISV-3289] Update UMB connection process and change sleep time

### PR DESCRIPTION
**Pull request by wcheang**

### CODE REVIEW

**Review by mporrato — APPROVED** [review]
Looks good to me, but have you considered passing `wait=True` when establishing the connection to the stomp server [1] or using the `wait_for_connection` method of the Transport class [2]? It would simplify your code a lot.

[1] http://jasonrbriggs.github.io/stomp.py/api.html#stomp.protocol.Protocol12.connect
[2] http://jasonrbriggs.github.io/stomp.py/stomp.html#stomp.transport.BaseTransport.wait_for_connection

**Review by haripate — APPROVED** [review]
LGTM

**Comment by wcheang** [comment]
> Looks good to me, but have you considered passing `wait=True` when establishing the connection to the stomp server [1] or using the `wait_for_connection` method of the Transport class [2]? It would simplify your code a lot.
> 
> [1] http://jasonrbriggs.github.io/stomp.py/api.html#stomp.protocol.Protocol12.connect [2] http://jasonrbriggs.github.io/stomp.py/stomp.html#stomp.transport.BaseTransport.wait_for_connection

Thank you for the suggestion @mporrato. I looked into setting `wait=True`, and it actually calls `wait_for_connection()`, checks the `is_connected()`, and throws an exception if connection is unsuccessful. This simplifies the code a good bit. I have updated the code. Please review again.

**Review by mporrato — APPROVED** [review]
Yes, I also suggested the `wait_for_connection` approach just in case you thought it was necessary to have a cap on the connection time.

LGTM :+1:

**Pull request merged**
